import { store } from "./store";
import {
  newBooksSlice,
  userSlice,
  fetchNewBooks,
  signUp,
  signIn,
  signOut,
  clearErrors,
  bookSlice,
  fetchBook,
  fetchBooksBySearch,
  incrementPage,
  decrementPage,
  searchBooksSlice,
  clearSearch,
  setPage,
} from "./features";
import {
  useGetNewBooks,
  useGetError,
  useGetIsLoading,
  useGetUserIsLoading,
  useGetUser,
  useGetUserError,
  useGetUserIsLoggedIn,
  useGetBook,
  useGetBookIsLoading,
  useGetBookError,
  useGetSearchBooks,
  useGetSearchBooksIsLoading,
  useGetSearchBooksError,
  useGetSearchBooksPage,
  useGetSearchBooksTotal,
} from "./selectors";

export {
  store,
  newBooksSlice,
  useGetNewBooks,
  useGetError,
  useGetIsLoading,
  useGetUserIsLoading,
  useGetUser,
  useGetUserError,
  useGetUserIsLoggedIn,
  userSlice,
  fetchNewBooks,
  signUp,
  signIn,
  signOut,
  clearErrors,
  bookSlice,
  fetchBook,
  useGetBook,
  useGetBookIsLoading,
  useGetBookError,
  fetchBooksBySearch,
  incrementPage,
  decrementPage,
  searchBooksSlice,
  useGetSearchBooks,
  useGetSearchBooksIsLoading,
  useGetSearchBooksError,
  useGetSearchBooksPage,
  useGetSearchBooksTotal,
  clearSearch,
  setPage,
};
